version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      .env
    environment:
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - '5432:5432'